Repository GDB-Online-Clone/http_web_server_c, pull requests merged in 2024-11, with the labels that each got.

#21 Refactor HTTP Header and Comment Cleanup
  src/http.h
  src/main.c
Labels: refactoring

#23 feat: HTTP 쿼리 파라미터 파싱 및 메모리 관리 기능 구현
  src/http.h
  src/main.c
Labels: feat, query-parameter

#37 feat: Feature/http_header `parse_http_headers()` `parse_http_header()` `insert_header()` 등 구현 및 추가
  src/http.h
  src/main.c
  src/utility.c
  src/utility.h
Labels: feat, http-header, utility

#58 Fix Makefile Issues: Shared Library Build Errors and .so File Naming Fixes
  Makefile
  src/http.h
Labels: chore

#61 Feature/http request
  .gitignore
  Doxyfile
  Makefile
  src/http.h
  src/main.c
  src/utility.c
  src/utility.h
Labels: feat

#75 Build,Test,CI: 유닛 테스트 환경 구축 및 Github Actions 연동을 통한 자동화 테스트 설정 + Makefile 수정
  .github/workflows/ci.yml
  Makefile
  test/unittest.c
Labels: test, build

#106 feat: Add Structures and Functions for Route Handling
  src/http.c
  src/http.h
  src/utility.h
  test/unittest.c
Labels: feat, http-header, utility, route

#113 [Redo] feat: Add Structures and Functions for Route Handling
  src/http.c
  test/unittest.c
Labels: chore

#152 Feature/gdb online
  src/main.c
Labels: feat
